import "@/styles/globals.css";

import type { AppProps } from "next/app";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

import PageLayout from "@/layout";
import ChatAssistant from "@/components/ChatAssistant";
import AppToaster from "@/components/AppToaster";
import { ApiProvider } from "@/context/ApiContext";
import { isGuestPath, isPlanPath, MEMBERSHIP_REQUIRED_EVENT, PLANS_PATH } from "@/lib/auth/constants";
import ReduxProvider from "@/store/ReduxProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const BARE_ROUTES = ["/dashboard/pay"];

const NO_FOOTER_ROUTES = ["/dashboard"];

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const { pathname } = router;
  const showChrome =
    !isGuestPath(pathname) && !BARE_ROUTES.includes(pathname);
  const showFooter = showChrome && !NO_FOOTER_ROUTES.includes(pathname);

  useEffect(() => {
    function onMembershipRequired() {
      if (isPlanPath(pathname)) return;
      void router.replace(PLANS_PATH);
    }

    window.addEventListener(MEMBERSHIP_REQUIRED_EVENT, onMembershipRequired);
    return () => {
      window.removeEventListener(
        MEMBERSHIP_REQUIRED_EVENT,
        onMembershipRequired,
      );
    };
  }, [pathname, router]);

  useEffect(() => {
    if (showChrome) return;

    // Keep page scrollable on mobile; only lock horizontal overflow.
    document.documentElement.style.overflowX = "hidden";
    document.body.style.overflowX = "hidden";
    document.body.style.background = "#09090b";

    return () => {
      document.documentElement.style.overflowX = "";
      document.body.style.overflowX = "";
      document.body.style.background = "";
    };
  }, [showChrome]);

  return (
    <>
      <Head>
        <title>Movie Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ReduxProvider>
        <ApiProvider>
          <div
            className={`${poppins.variable} ${poppins.className} flex min-h-dvh flex-col antialiased`}
          >
            <PageLayout showHeader={showChrome} showFooter={showFooter}>
              <Component {...pageProps} />
            </PageLayout>
            {showChrome && <ChatAssistant />}
            <AppToaster />
          </div>
        </ApiProvider>
      </ReduxProvider>
    </>
  );
}
