import "@/styles/globals.css";

import type { AppProps } from "next/app";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

import PageLayout from "@/layout";
import ChatAssistant from "@/components/ChatAssistant";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const BARE_ROUTES = ["/login", "/signup", "/auth"];

export default function App({ Component, pageProps }: AppProps) {
  const { pathname } = useRouter();
  const showChrome = !BARE_ROUTES.includes(pathname);

  useEffect(() => {
    if (showChrome) return;

    document.documentElement.style.overflow = "hidden";
    document.body.style.overflow = "hidden";
    document.body.style.background = "#ffffff";

    return () => {
      document.documentElement.style.overflow = "";
      document.body.style.overflow = "";
      document.body.style.background = "";
    };
  }, [showChrome]);

  return (
    <>
      <Head>
        <title>Movie Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
        className={`${poppins.variable} ${poppins.className} flex min-h-dvh flex-col antialiased`}
      >
        <PageLayout showHeader={showChrome} showFooter={showChrome}>
          <Component {...pageProps} />
        </PageLayout>
        {showChrome && <ChatAssistant />}
      </div>
    </>
  );
}
